CREATE TABLE TMP_MSC_DATA (
    NOMBRE_VICTIMA              VARCHAR(200),
    APELLIDO_VICTIMA	        VARCHAR(200),
    DIRECCION_VICTIMA	        VARCHAR(200),
    FECHA_PRIMERA_SOSPECHA	    DATE,
    FECHA_CONFIRMACION          DATE,
    FECHA_MUERTE                DATE,
    ESTADO_VICTIMA              VARCHAR(200),
    NOMBRE_ASOCIADO             VARCHAR(200),
    APELLIDO_ASOCIADO           VARCHAR(200),
    FECHA_CONOCIO               DATE,
    CONTACTO_FISICO             VARCHAR(200),
    FECHA_INICIO_CONTACTO       DATE,
    FECHA_FIN_CONTACTO          DATE,
    NOMBRE_HOSPITAL             VARCHAR(200),
    DIRECCION_HOSPITAL          VARCHAR(200),
    UBICACION_VICTIMA           VARCHAR(200),
    FECHA_LLEGADA               DATE,
    FECHA_RETIRO                DATE,
    TRATAMIENTO                 VARCHAR(200),
    EFECTIVIDAD                 INT,
    FECHA_INICIO_TRATAMIENTO    DATE,
    FECHA_FIN_TRATAMIENTO       DATE,
    EFECTIVIDAD_EN_VICTIMA      INT
);


---- TABLAS
CREATE TABLE VICTIMA (
        ID                      INT GENERATED AS IDENTITY,
        NOMBRE                  VARCHAR(200),
        APELLIDO                VARCHAR(200),
        DIRECCION               VARCHAR(200),
        FECHA_PRIMERA_SOSPECHA  DATE,
        FECHA_CONFIRMACION      DATE,
        FECHA_MUERTE            DATE,
        ESTADO                  VARCHAR(255)
);


--- INSERTAR INFORMACION
INSERT INTO VICTIMA(NOMBRE, APELLIDO, DIRECCION, FECHA_PRIMERA_SOSPECHA, FECHA_CONFIRMACION, FECHA_MUERTE, ESTADO)
SELECT
    DISTINCT NOMBRE_VICTIMA,
    APELLIDO_VICTIMA,
    DIRECCION_VICTIMA,
    FECHA_PRIMERA_SOSPECHA,
    FECHA_CONFIRMACION,
    FECHA_MUERTE,
    ESTADO_VICTIMA
FROM TMP_MSC_DATA
WHERE NOMBRE_VICTIMA IS NOT NULL
